### ISSUE TITLE
Add missing keyring backend

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof_pg#18]
When using oemof.db in a fresh (virtual) environment database access tools fail due to missing keyring backend, see

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/guido/virtualenvs/elesplan_m/lib/python3.4/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/home/guido/virtualenvs/elesplan_m/lib/python3.4/site-packages/keyring/backends/fail.py", line 18, in get_password
    raise RuntimeError("No recommended backend was available. Install the "
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```

I suggest to add keyrings.alt to the dependencies list in order to solve this issue.

@oemof/oemof-db feedback on this is welcome!

**Comment by uvchik** [comment]
I do not really understand the consequences of the keyring changes but I think we should add `keyrings.alt` until we know it better.
