### ISSUE TITLE
Keyring(s) packages make oemof.db fail on import

### ISSUE THREAD

**Issue by gplssm** [oemof/oemof_pg#30]
Updated versions of the dependent packages keyring (10.3.1) and keyrings.alt (2.1) induce import errors.

```
import oemof.db as db
```
results in following error

```
Error initializing plugin Gnome = keyrings.alt.Gnome.
Traceback (most recent call last):
  File "/home/jonathan/python/virtualenvs/dingo/lib/python3.5/site-packages/keyring/backend.py", line 167, in _load_plugins
    init_func = ep.load()
  File "/home/jonathan/python/virtualenvs/dingo/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/jonathan/python/virtualenvs/dingo/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jonathan/python/virtualenvs/dingo/lib/python3.5/site-packages/keyrings/alt/Gnome.py", line 11, in <module>
    from keyring.py27compat import unicode_str
ImportError: cannot import name 'unicode_str'
```

A quick work-around is to limit versions of these packages to 
 - keyring 10.3.0
 - keyrings.alt 2.0

The actual problem is something related to the SecretStorage backend or similar. Haven't figured out this in detail. This is for some reason only available in Gnome.
Thus, maybe the above mentioned work-around may work as solution to fix this issue.

**Comment by gnn** [comment]
This has been fixed upstream with `keyrings.alt` version `2.2`.
I'm going to put a version restriction for `!= 2.1` into the requirements and close this afterwards.

**Comment by gplssm** [comment]
Thx!
